export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_RESET_ACCOUNT = 'AUTH_RESET_ACCOUNT'
export const AUTH_RESET_ACCOUNT_SUCCESS = 'AUTH_RESET_ACCOUNT_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

