# Generated by Django 3.2.9 on 2021-12-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='pmwassini@gmail.com', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='Peter Mwangi', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(default='Maina', max_length=255, verbose_name='last name')),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='pmwassini@gmail.com', max_length=255, unique=True, verbose_name='email address')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/profile/avatars/')),
                ('phone', models.CharField(default='+254796487662', max_length=13)),
                ('address', models.CharField(default='Nakuru, Kenya', max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/profile/resumes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
