# Generated by Django 3.2.9 on 2022-01-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myaccount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='pmwassini@gmail.com', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='Peter Mwangi', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(default='Maina', max_length=255, verbose_name='last name')),
                ('token', models.CharField(blank=True, max_length=50, null=True, verbose_name='custom auth token')),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='message email')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='pmwassini@gmail.com', max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(default='+254796487662', max_length=13)),
                ('address', models.CharField(default='Nakuru, Kenya', max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/profile/resumes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('cartegory', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('project_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to=myaccount.models.file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
