# Generated by Django 3.2.9 on 2021-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='custom auth token'),
        ),
    ]
