# Generated by Django 3.2.9 on 2022-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_projectsample_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='icon',
            field=models.CharField(default='react', max_length=255),
        ),
    ]
